
INSERT INTO `bookcases` (`id`, `name`) VALUES
('000', 'Computer science, information & general works'),
('100', 'Philosophy & psychology'),
('200', 'Religion'),
('300', 'Social sciences'),
('400', 'Language'),
('500', 'Science'),
('600', 'Technology'),
('700', 'Arts & recreation'),
('800', 'Literature'),
('900', 'History & geography ');


INSERT INTO `bookcategories` (`id`, `name`, `book_case_id`) VALUES
('000', 'Computer science, knowledge & systems', '000'),
('010', 'Bibliographies', '000'),
('020', 'Library & information sciences', '000'),
('030', 'Encyclopedias & books of facts', '000'),
('040', '[Unassigned]', '000'),
('050', 'Magazines, journals & serials', '000'),
('060', 'Associations, organizations & museums', '000'),
('070', 'News media, journalism & publishing', '000'),
('080', 'Quotations', '000'),
('090', 'Manuscripts & rare books', '000'),
('100', 'Philosophy', '100'),
('110', 'Metaphysics', '100'),
('120', 'Epistemology', '100'),
('130', 'Parapsychology & occultism', '100'),
('140', 'Philosophical schools of thought', '100'),
('150', 'Psychology', '100'),
('160', 'Philosophical logic', '100'),
('170', 'Ethics', '100'),
('180', 'Ancient, medieval & eastern philosophy', '100'),
('190', 'Modern western philosophy', '100'),
('200', 'Religion', '200'),
('210', 'Philosophy & theory of religion', '200'),
('220', 'The Bible', '200'),
('230', 'Christianity', '200'),
('240', 'Christian practice & observance', '200'),
('250', 'Christian pastoral practice & religious orders', '200'),
('260', 'Christian organization, social work & worship', '200'),
('270', 'History of Christianity', '200'),
('280', 'Christian denominations', '200'),
('290', 'Other religions', '200'),
('300', 'Social sciences, sociology & anthropology', '300'),
('310', 'Statistics', '300'),
('320', 'Political science', '300'),
('330', 'Economics', '300'),
('340', 'Law', '300'),
('350', 'Public administration & military science', '300'),
('360', 'Social problems & social services', '300'),
('370', 'Education', '300'),
('380', 'Commerce, communications & transportation', '300'),
('390', 'Customs, etiquette & folklore', '300'),
('400', 'Language', '400'),
('410', 'Linguistics', '400'),
('420', 'English & Old English languages', '400'),
('430', 'German & related languages', '400'),
('440', 'French & related languages', '400'),
('450', 'Italian, Romanian & related languages', '400'),
('460', 'Spanish, Portuguese, Galician', '400'),
('470', 'Latin & Italic languages', '400'),
('480', 'Classical & modern Greek languages', '400'),
('490', 'Other languages', '400'),
('500', 'Science', NULL),
('510', 'Mathematics', NULL),
('520', 'Astronomy', NULL),
('530', 'Physics', NULL),
('540', 'Chemistry', NULL),
('550', 'Earth sciences & geology', NULL),
('560', 'Fossils & prehistoric life', NULL),
('570', 'Biology', NULL),
('580', 'Plants (Botany)', NULL),
('590', 'Animals (Zoology)', NULL),
('600', 'Technology', NULL),
('610', 'Medicine & health', NULL),
('620', 'Engineering', NULL),
('630', 'Agriculture', NULL),
('640', 'Home & family management', NULL),
('650', 'Management & public relations', NULL),
('660', 'Chemical engineering', NULL),
('670', 'Manufacturing', NULL),
('680', 'Manufacture for specific uses', NULL),
('690', 'Construction of buildings', NULL),
('700', 'Arts', NULL),
('710', 'Area planning & landscape architecture', NULL),
('720', 'Architecture', NULL),
('730', 'Sculpture, ceramics & metalwork', NULL),
('740', 'Graphic arts & decorative arts', NULL),
('750', 'Painting', NULL),
('760', 'Printmaking & prints', NULL),
('770', 'Photography, computer art, film, video', NULL),
('780', 'Music', NULL),
('790', 'Sports, games & entertainment', NULL),
('800', 'Literature, rhetoric & criticism', NULL),
('810', 'American literature in English', NULL),
('820', 'English & Old English literatures', NULL),
('830', 'German & related literatures', NULL),
('840', 'French & related literatures', NULL),
('850', 'Italian, Romanian & related literatures', NULL),
('860', 'Spanish, Portuguese, Galician literatures', NULL),
('870', 'Latin & Italic literatures', NULL),
('880', 'Classical & modern Greek literatures', NULL),
('890', 'Other literatures', NULL),
('900', 'History', NULL),
('910', 'Geography & travel', NULL),
('920', 'Biography & genealogy', NULL),
('930', 'History of ancient world (to ca. 499)', NULL),
('940', 'History of Europe', NULL),
('950', 'History of Asia', NULL),
('960', 'History of Africa', NULL),
('970', 'History of North America', NULL),
('980', 'History of South America', NULL),
('990', 'History of other areas', NULL);


INSERT INTO `branches` (`id`, `name`, `category_id`) VALUES
('000', 'Computer science, information, general works', NULL),
('001', 'Knowledge', NULL),
('002', 'The book', NULL),
('003', 'Systems', NULL),
('004', 'Computer science', NULL),
('005', 'Computer programming, programs, data, security', NULL),
('006', 'Special computer methods', NULL),
('007', '[Unassigned]', NULL),
('008', '[Unassigned]', NULL),
('009', '[Unassigned]', NULL),
('010', 'Bibliography', NULL),
('011', 'Bibliographies and catalogs', NULL),
('012', 'Bibliographies and catalogs of individuals', NULL),
('013', '[Unassigned]', NULL),
('014', 'Of anonymous & pseudonymous works', NULL),
('015', 'Of works from specific places', NULL),
('016', 'Of works on specific subjects', NULL),
('017', 'Of works held in specific collections or offered for sale', NULL),
('018', '[Unassigned]', NULL),
('019', '[Unassigned]', NULL),
('020', 'Library and information sciences', NULL),
('021', 'Relationships of libraries and archives', NULL),
('022', 'Administration of physical plant', NULL),
('023', 'Personnel management', NULL),
('024', '[Unassigned]', NULL),
('025', 'Operations of libraries and archives', NULL),
('026', 'Libraries and archives devoted to specific subjects', NULL),
('027', 'General libraries and archives', NULL),
('028', 'Reading and use of other information media', NULL),
('029', '[Unassigned]', NULL),
('030', 'General encyclopedic works', NULL),
('031', 'General encyclopedic works in American English', NULL),
('032', 'General encyclopedic works in English', NULL),
('033', 'Encyclopedias in other Germanic languages', NULL),
('034', 'Encyclopedias in French, Occitan, Catalan', NULL),
('035', 'Encyclopedias in Italian, Romanian & related languages', NULL),
('036', 'Encyclopedias in Spanish, Portuguese, Galician', NULL),
('037', 'General encyclopedic works in Slavic languages', NULL),
('038', 'General encyclopedic works in Scandinavian languages', NULL),
('039', 'General encyclopedic works in other languages', NULL),
('040', 'Unassigned', NULL),
('041', 'Unassigned', NULL),
('042', 'Unassigned', NULL),
('043', 'Unassigned', NULL),
('044', 'Unassigned', NULL),
('045', 'Unassigned', NULL),
('046', 'Unassigned', NULL),
('047', 'Unassigned', NULL),
('048', 'Unassigned', NULL),
('049', 'Unassigned', NULL),
('050', 'General serial publications', NULL),
('051', 'General serial publications in American English', NULL),
('052', 'General serial publications in English', NULL),
('053', 'Serials in other Germanic languages', NULL),
('054', 'Serials in French, Occitan, Catalan', NULL),
('055', 'Serials in Italian, Romanian & related languages', NULL),
('056', 'Serials in Spanish, Portuguese, Galician', NULL),
('057', 'General serial publications in Slavic languages', NULL),
('058', 'Serials in Scandinavian languages', NULL),
('059', 'General serial publications in other languages', NULL),
('060', 'General organizations and museology', NULL),
('061', 'General organizations in North America', NULL),
('062', 'General organizations in British Isles', NULL),
('063', 'General organizations in Germany', NULL),
('064', 'General organizations in France and Monaco', NULL),
('065', 'General organizations in Italy', NULL),
('066', 'General organizations in Spain', NULL),
('067', 'General organizations in Russia', NULL),
('068', 'General organizations in other geographic areas', NULL),
('069', 'Museology (Museum science)', NULL),
('070', 'Documentary, educational, news media; journalism', NULL),
('071', 'Journalism and newspapers in North America', NULL),
('072', 'Journalism and newspapers in British Isles', NULL),
('073', 'Journalism and newspapers in Germany', NULL),
('074', 'Journalism and newspapers in France and Monaco', NULL),
('075', 'Journalism and newspapers in Italy', NULL),
('076', 'Journalism and newspapers in Spain', NULL),
('077', 'Journalism and newspapers in Russia', NULL),
('078', 'Journalism and newspapers in Scandinavia', NULL),
('079', 'Newspapers in other geographic areas', NULL),
('080', 'General collections', NULL),
('081', 'General collections in American English', NULL),
('082', 'General collections in English', NULL),
('083', 'General collections in other Germanic languages', NULL),
('084', 'General collections in French, Occitan, Catalan', NULL),
('085', 'Collections in Italian, Romanian & related languages', NULL),
('086', 'Collections in Spanish, Portuguese, Galician', NULL),
('087', 'General collections in Slavic languages', NULL),
('088', 'General collections in Scandinavian languages', NULL),
('089', 'General collections in other languages', NULL),
('090', 'Manuscripts, rare books', NULL),
('091', 'Manuscripts', NULL),
('092', 'Block books', NULL),
('093', 'Incunabula', NULL),
('094', 'Printed books', NULL),
('095', 'Books notable for bindings', NULL),
('096', 'Books notable for illustrations and materials', NULL),
('097', 'Books notable for ownership or origin', NULL),
('098', 'Prohibited works, forgeries, hoaxes', NULL),
('099', 'Books notable for format', NULL),
('100', 'Philosophy & psychology', NULL),
('101', 'Theory of philosophy', NULL),
('102', 'Miscellany of philosophy', NULL),
('103', 'Dictionaries & encyclopedias', NULL),
('104', '[Unassigned]', NULL),
('105', 'Serial publications of philosophy', NULL),
('106', 'Organizations & management', NULL),
('107', 'Education, research & related topics', NULL),
('108', 'Groups of people', NULL),
('109', 'History and collected biography', NULL),
('110', 'Metaphysics', NULL),
('111', 'Ontology', NULL),
('112', '[Unassigned]', NULL),
('113', 'Cosmology (Philosophy of nature)', NULL),
('114', 'Space', NULL),
('115', 'Time', NULL),
('116', 'Change', NULL),
('117', 'Structure', NULL),
('118', 'Force and energy', NULL),
('119', 'Number and quantity', NULL),
('120', 'Epistemology, causation, humankind', NULL),
('121', 'Epistemology (Theory of knowledge)', NULL),
('122', 'Causation', NULL),
('123', 'Determinism and indeterminism', NULL),
('124', 'Teleology', NULL),
('125', '[Unassigned]', NULL),
('126', 'The self', NULL),
('127', 'The unconscious and the subconscious', NULL),
('128', 'Humankind', NULL),
('129', 'Origin and destiny of individual souls', NULL),
('130', 'Parapsychology and occultism', NULL),
('131', 'Parapsychological and occult methods', NULL),
('132', '[Unassigned]', NULL),
('133', 'Specific topics in parapsychology & occultism', NULL),
('134', '[Unassigned]', NULL),
('135', 'Dreams and mysteries', NULL),
('136', '[Unassigned]', NULL),
('137', 'Divinatory graphology', NULL),
('138', 'Physiognomy', NULL),
('139', 'Phrenology', NULL),
('140', 'Specific philosophical schools', NULL),
('141', 'Idealism and related systems', NULL),
('142', 'Critical philosophy', NULL),
('143', 'Bergsonism and intuitionism', NULL),
('144', 'Humanism and related systems', NULL),
('145', 'Sensationalism', NULL),
('146', 'Naturalism and related systems', NULL),
('147', 'Pantheism and related systems', NULL),
('148', 'Dogmatism, eclecticism, liberalism, etc.', NULL),
('149', 'Other philosophical systems and doctrines', NULL),
('150', 'Psychology', NULL),
('151', '[Unassigned]', NULL),
('152', 'Perception, movement, emotions & drives', NULL),
('153', 'Conscious mental processes & intelligence', NULL),
('154', 'Subconscious & altered states', NULL),
('155', 'Differential & developmental psychology', NULL),
('156', 'Comparative psychology', NULL),
('157', '[Unassigned]', NULL),
('158', 'Applied psychology', NULL),
('159', '[Unassigned]', NULL),
('160', 'Philosophical logic', NULL),
('161', 'Induction', NULL),
('162', 'Deduction', NULL),
('163', '[Unassigned]', NULL),
('164', '[Unassigned]', NULL),
('165', 'Fallacies and sources of error', NULL),
('166', 'Syllogisms', NULL),
('167', 'Hypotheses', NULL),
('168', 'Argument and persuasion', NULL),
('169', 'Analogy', NULL),
('170', 'Ethics (Moral philosophy)', NULL),
('171', 'Ethical systems', NULL),
('172', 'Political ethics', NULL),
('173', 'Ethics of family relationships', NULL),
('174', 'Occupational ethics', NULL),
('175', 'Ethics of recreation & leisure', NULL),
('176', 'Ethics of sex and reproduction', NULL),
('177', 'Ethics of social relations', NULL),
('178', 'Ethics of consumption', NULL),
('179', 'Other ethical norms', NULL),
('180', 'Ancient, medieval, eastern philosophy', NULL),
('181', 'Eastern philosophy', NULL),
('182', 'Pre-Socratic Greek philosophies', NULL),
('183', 'Sophistic, Socratic, related philosophies', NULL),
('184', 'Platonic philosophy', NULL),
('185', 'Aristotelian philosophy', NULL),
('186', 'Skeptic and Neoplatonic philosophies', NULL),
('187', 'Epicurean philosophy', NULL),
('188', 'Stoic philosophy', NULL),
('189', 'Medieval western philosophy', NULL),
('190', 'Modern western philosophy', NULL),
('191', 'Philosophy of United States and Canada', NULL),
('192', 'Philosophy of British Isles', NULL),
('193', 'Philosophy of Germany and Austria', NULL),
('194', 'Philosophy of France', NULL),
('195', 'Philosophy of Italy', NULL),
('196', 'Philosophy of Spain and Portugal', NULL),
('197', 'Philosophy of Russia', NULL),
('198', 'Philosophy of Scandinavia and Finland', NULL),
('199', 'Philosophy of other geographic areas', NULL),
('200', 'Religion', NULL),
('201', 'Religious mythology & social theology', NULL),
('202', 'Doctrines', NULL),
('203', 'Public worship and other practices', NULL),
('204', 'Religious experience, life, practice', NULL),
('205', 'Religious ethics', NULL),
('206', 'Leaders and organization', NULL),
('207', 'Missions and religious education', NULL),
('208', 'Sources', NULL),
('209', 'Sects and reform movements', NULL),
('210', 'Philosophy and theory of religion', NULL),
('211', 'Concepts of God', NULL),
('212', 'Existence, knowability & attributes of God', NULL),
('213', 'Creation', NULL),
('214', 'Theodicy', NULL),
('215', 'Science and religion', NULL),
('216', '[Unassigned]', NULL),
('217', '[Unassigned]', NULL),
('218', 'Humankind', NULL),
('219', '[Unassigned]', NULL),
('220', 'Bible', NULL),
('221', 'Old Testament (Tanakh)', NULL),
('222', 'Historical books of Old Testament', NULL),
('223', 'Poetic books of Old Testament', NULL),
('224', 'Prophetic books of Old Testament', NULL),
('225', 'New Testament', NULL),
('226', 'Gospels and Acts', NULL),
('227', 'Epistles', NULL),
('228', 'Revelation (Apocalypse)', NULL),
('229', 'Apocrypha and pseudepigrapha', NULL),
('230', 'Christianity', NULL),
('231', 'God', NULL),
('232', 'Jesus Christ and his family', NULL),
('233', 'Humankind', NULL),
('234', 'Salvation and grace', NULL),
('235', 'Spiritual beings', NULL),
('236', 'Eschatology', NULL),
('237', '[Unassigned]', NULL),
('238', 'Creeds & catechisms', NULL),
('239', 'Apologetics and polemics', NULL),
('240', 'Christian moral and devotional theology', NULL),
('241', 'Christian ethics', NULL),
('242', 'Devotional literature', NULL),
('243', 'Evangelistic writings for individuals', NULL),
('244', '[Unassigned]', NULL),
('245', '[Unassigned]', NULL),
('246', 'Use of art in Christianity', NULL),
('247', 'Church furnishings and related articles', NULL),
('248', 'Christian experience, practice, life', NULL),
('249', 'Christian observances in family life', NULL),
('250', 'Local Christian church and religious orders', NULL),
('251', 'Preaching (Homiletics)', NULL),
('252', 'Texts of sermons', NULL),
('253', 'Pastoral work (Pastoral theology)', NULL),
('254', 'Local church administration', NULL),
('255', 'Religious congregations and orders', NULL),
('256', '[Unassigned] ', NULL),
('257', '[Unassigned] ', NULL),
('258', '[Unassigned]', NULL),
('259', 'Pastoral care of families & kinds of persons', NULL),
('260', 'Christian social and ecclesiastical theology', NULL),
('261', 'Social theology and interreligious relations', NULL),
('262', 'Ecclesiology', NULL),
('263', 'Days, times, places of religious observance', NULL),
('264', 'Public worship', NULL),
('265', 'Sacraments, other rites and acts', NULL),
('266', 'Missions', NULL),
('267', 'Associations for religious work', NULL),
('268', 'Religious education', NULL),
('269', 'Spiritual renewal', NULL),
('270', 'History, geographic treatment, biography', NULL),
('271', 'Religious orders in church history', NULL),
('272', 'Persecutions in general church history', NULL),
('273', 'Doctrinal controversies & heresies', NULL),
('274', 'History of Christianity in Europe', NULL),
('275', 'History of Christianity in Asia', NULL),
('276', 'History of Christianity in Africa', NULL),
('277', 'History of Christianity in North America', NULL),
('278', 'History of Christianity in South America', NULL),
('279', 'History of Christianity in other areas', NULL),
('280', 'Denominations & sects of Christian church', NULL),
('281', 'Early church and Eastern churches', NULL),
('282', 'Roman Catholic Church', NULL),
('283', 'Anglican churches', NULL),
('284', 'Protestants of Continental origin', NULL),
('285', 'Presbyterian, Reformed & Congregational', NULL),
('286', 'Baptist, Restoration & Adventist', NULL),
('287', 'Methodist and related churches', NULL),
('288', '[Unassigned]', NULL),
('289', 'Other denominations and sects', NULL),
('290', 'Other religions', NULL),
('291', '[Unassigned]', NULL),
('292', 'Classical religion (Greek & Roman religion)', NULL),
('293', 'Germanic religion', NULL),
('294', 'Religions of Indic origin', NULL),
('295', 'Zoroastrianism (Mazdaism, Parseeism)', NULL),
('296', 'Judaism', NULL),
('297', 'Islam, Babism & Bahai Faith', NULL),
('298', '(Optional number)', NULL),
('299', 'Religions not provided for elsewhere', NULL),
('300', 'Social sciences', NULL),
('301', 'Sociology and anthropology', NULL),
('302', 'Social interaction', NULL),
('303', 'Social processes', NULL),
('304', 'Factors affecting social behavior', NULL),
('305', 'Groups of people', NULL),
('306', 'Culture and institutions', NULL),
('307', 'Communities ', NULL),
('308', '[Unassigned] ', NULL),
('309', '[Unassigned] ', NULL),
('310', 'Collections of general statistics', NULL),
('311', '[Unassigned] ', NULL),
('312', '[Unassigned]', NULL),
('313', '[Unassigned]', NULL),
('314', 'General statistics of Europe', NULL),
('315', 'General statistics of Asia', NULL),
('316', 'General statistics of Africa', NULL),
('317', 'General statistics of North America', NULL),
('318', 'General statistics of South America', NULL),
('319', 'General statistics of other areas', NULL),
('320', 'Political science (Politics and government)', NULL),
('321', 'Systems of governments and states', NULL),
('322', 'Relation of state to organized groups', NULL),
('323', 'Civil and political rights', NULL),
('324', 'The political process', NULL),
('325', 'International migration and colonization', NULL),
('326', 'Slavery and emancipation', NULL),
('327', 'International relations', NULL),
('328', 'The legislative process', NULL),
('329', '[Unassigned]', NULL),
('330', 'Economics', NULL),
('331', 'Labor economics', NULL),
('332', 'Financial economics', NULL),
('333', 'Economics of land and energy', NULL),
('334', 'Cooperatives', NULL),
('335', 'Socialism and related systems', NULL),
('336', 'Public finance', NULL),
('337', 'International economics', NULL),
('338', 'Production', NULL),
('339', 'Macroeconomics and related topics', NULL),
('340', 'Law', NULL),
('341', 'Law of nations', NULL),
('342', 'Constitutional and administrative law', NULL),
('343', 'Military, tax, trade & industrial law', NULL),
('344', 'Labor, social, education & cultural law', NULL),
('345', 'Criminal law', NULL),
('346', 'Private law', NULL),
('347', 'Procedure and courts', NULL),
('348', 'Laws, regulations, cases', NULL),
('349', 'Law of specific jurisdictions & areas', NULL),
('350', 'Public administration and military science', NULL),
('351', 'Public administration', NULL),
('352', 'General considerations of public administration', NULL),
('353', 'Specific fields of public administration', NULL),
('354', 'Administration of economy & environment', NULL),
('355', 'Military science', NULL),
('356', 'Foot forces & warfare', NULL),
('357', 'Mounted forces & warfare', NULL),
('358', 'Air & other specialized forces', NULL),
('359', 'Sea forces and warfare', NULL),
('360', 'Social problems and services; associations', NULL),
('361', 'Social problems and services', NULL),
('362', 'Social problems and services to groups', NULL),
('363', 'Other social problems and services', NULL),
('364', 'Criminology', NULL),
('365', 'Penal and related institutions', NULL),
('366', 'Secret associations and societies', NULL),
('367', 'General clubs', NULL),
('368', 'Insurance', NULL),
('369', 'Associations', NULL),
('370', 'Education', NULL),
('371', 'Schools and their activities; special education', NULL),
('372', 'Primary education (Elementary education)', NULL),
('373', 'Secondary education', NULL),
('374', 'Adult education', NULL),
('375', 'Curricula', NULL),
('376', '[Unassigned]', NULL),
('377', '[Unassigned]', NULL),
('378', 'Higher education (Tertiary education)', NULL),
('379', 'Public policy issues in education', NULL),
('380', 'Commerce, communications, transportation', NULL),
('381', 'Commerce (Trade)', NULL),
('382', 'International commerce (Foreign trade)', NULL),
('383', 'Postal communication', NULL),
('384', 'Communications', NULL),
('385', 'Railroad transportation', NULL),
('386', 'Inland waterway and ferry transportation', NULL),
('387', 'Water, air, space transportation', NULL),
('388', 'Transportation', NULL),
('389', 'Metrology and standardization', NULL),
('390', 'Customs, etiquette, folklore', NULL),
('391', 'Costume and personal appearance', NULL),
('392', 'Customs of life cycle and domestic life', NULL),
('393', 'Death customs', NULL),
('394', 'General customs', NULL),
('395', 'Etiquette (Manners)', NULL),
('396', '[Unassigned]', NULL),
('397', '[Unassigned]', NULL),
('398', 'Folklore', NULL),
('399', 'Customs of war and diplomacy', NULL),
('400', 'Language', NULL),
('401', 'Philosophy and theory', NULL),
('402', 'Miscellany', NULL),
('403', 'Dictionaries & encyclopedias', NULL),
('404', 'Special topics of language', NULL),
('405', 'Serial publications', NULL),
('406', 'Organizations and management', NULL),
('407', 'Education, research, related topics', NULL),
('408', 'Groups of people', NULL),
('409', 'Geographic treatment and biography', NULL),
('410', 'Linguistics', NULL),
('411', 'Writing systems', NULL),
('412', 'Etymology', NULL),
('413', 'Dictionaries', NULL),
('414', 'Phonology & phonetics', NULL),
('415', 'Grammar', NULL),
('416', '[Unassigned]', NULL),
('417', 'Dialectology and historical linguistics', NULL),
('418', 'Applied linguistics', NULL),
('419', 'Sign languages', NULL),
('420', 'English & Old English (Anglo-Saxon)', NULL),
('421', 'Writing system, phonology, phonetics', NULL),
('422', 'Etymology of standard English', NULL),
('423', 'Dictionaries of standard English', NULL),
('424', '[Unassigned]', NULL),
('425', 'Grammar of standard English', NULL),
('426', '[Unassigned]', NULL),
('427', 'English language variations', NULL),
('428', 'Standard English usage', NULL),
('429', 'Old English (Anglo-Saxon)', NULL),
('430', 'German and related languages', NULL),
('431', 'Writing system, phonology, phonetics', NULL),
('432', 'Etymology of standard German', NULL),
('433', 'Dictionaries of standard German', NULL),
('434', '[Unassigned]', NULL),
('435', 'Grammar of standard German', NULL),
('436', '[Unassigned]', NULL),
('437', 'German language variations', NULL),
('438', 'Standard German usage', NULL),
('439', 'Other Germanic languages', NULL),
('440', 'French & related Romance languages', NULL),
('441', 'Writing system, phonology, phonetics', NULL),
('442', 'Etymology of standard French', NULL),
('443', 'Dictionaries of standard French', NULL),
('444', '[Unassigned]', NULL),
('445', 'Grammar of standard French', NULL),
('446', '[Unassigned]', NULL),
('447', 'French language variations', NULL),
('448', 'Standard French usage', NULL),
('449', 'Occitan, Catalan, Franco-Provençal', NULL),
('450', 'Italian, Romanian & related languages', NULL),
('451', 'Writing system, phonology, phonetics', NULL),
('452', 'Etymology of standard Italian', NULL),
('453', 'Dictionaries of standard Italian', NULL),
('454', '[Unassigned]', NULL),
('455', 'Grammar of standard Italian', NULL),
('456', '[Unassigned]', NULL),
('457', 'Italian language variations', NULL),
('458', 'Standard Italian usage', NULL),
('459', 'Romanian, Rhaetian, Sardinian, Corsican', NULL),
('460', 'Spanish, Portuguese, Galician', NULL),
('461', 'Writing system, phonology, phonetics', NULL),
('462', 'Etymology of standard Spanish', NULL),
('463', 'Dictionaries of standard Spanish', NULL),
('464', '[Unassigned]', NULL),
('465', 'Grammar of standard Spanish', NULL),
('466', '[Unassigned]', NULL),
('467', 'Spanish language variations', NULL),
('468', 'Standard Spanish usage', NULL),
('469', 'Portuguese', NULL),
('470', 'Latin and related Italic languages', NULL),
('471', 'Writing system, phonology, phonetics', NULL),
('472', 'Etymology of classical Latin', NULL),
('473', 'Dictionaries of classical Latin', NULL),
('474', '[Unassigned]', NULL),
('475', 'Grammar of classical Latin', NULL),
('476', '[Unassigned]', NULL),
('477', 'Old, postclassical, Vulgar Latin', NULL),
('478', 'Classical Latin usage', NULL),
('479', 'Other Italic languages', NULL),
('480', 'Classical Greek; Hellenic languages', NULL),
('481', 'Writing system, phonology, phonetics', NULL),
('482', 'Etymology of classical Greek', NULL),
('483', 'Dictionaries of classical Greek', NULL),
('484', '[Unassigned]', NULL),
('485', 'Grammar of classical Greek', NULL),
('486', '[Unassigned]', NULL),
('487', 'Preclassical and postclassical Greek', NULL),
('488', 'Classical Greek usage', NULL),
('489', 'Other Hellenic languages', NULL),
('490', 'Other languages', NULL),
('491', 'East Indo-European and Celtic languages', NULL),
('492', 'Afro-Asiatic languages', NULL),
('493', 'Non-Semitic Afro-Asiatic languages', NULL),
('494', 'Altaic, Uralic, Hyperborean & Dravidian', NULL),
('495', 'Languages of east and southeast Asia', NULL),
('496', 'African languages', NULL),
('497', 'North American native languages', NULL),
('498', 'South American native languages', NULL),
('499', 'Austronesian & other languages', NULL),
('500', 'Natural sciences and mathematics', NULL),
('501', 'Philosophy and theory', NULL),
('502', 'Miscellany', NULL),
('503', 'Dictionaries & encyclopedias', NULL),
('504', '[Unassigned]', NULL),
('505', 'Serial publications', NULL),
('506', 'Organizations and management', NULL),
('507', 'Education, research, related topics', NULL),
('508', 'Natural history', NULL),
('509', 'History, geographic treatment, biography', NULL),
('510', 'Mathematics', NULL),
('511', 'General principles of mathematics', NULL),
('512', 'Algebra', NULL),
('513', 'Arithmetic', NULL),
('514', 'Topology', NULL),
('515', 'Analysis', NULL),
('516', 'Geometry', NULL),
('517', '[Unassigned]', NULL),
('518', 'Numerical analysis', NULL),
('519', 'Probabilities and applied mathematics', NULL),
('520', 'Astronomy and allied sciences', NULL),
('521', 'Celestial mechanics', NULL),
('522', 'Techniques, equipment & materials', NULL),
('523', 'Specific celestial bodies and phenomena', NULL),
('524', '[Unassigned]', NULL),
('525', 'Earth (Astronomical geography)', NULL),
('526', 'Mathematical geography', NULL),
('527', 'Celestial navigation', NULL),
('528', 'Ephemerides', NULL),
('529', 'Chronology', NULL),
('530', 'Physics', NULL),
('531', 'Classical mechanics', NULL),
('532', 'Fluid mechanics', NULL),
('533', 'Pneumatics (Gas mechanics)', NULL),
('534', 'Sound and related vibrations', NULL),
('535', 'Light and related radiation', NULL),
('536', 'Heat', NULL),
('537', 'Electricity and electronics', NULL),
('538', 'Magnetism', NULL),
('539', 'Modern physics', NULL),
('540', 'Chemistry and allied sciences', NULL),
('541', 'Physical chemistry', NULL),
('542', 'Techniques, equipment & materials', NULL),
('543', 'Analytical chemistry', NULL),
('544', '[Unassigned]', NULL),
('545', '[Unassigned]', NULL),
('546', 'Inorganic chemistry', NULL),
('547', 'Organic chemistry', NULL),
('548', 'Crystallography', NULL),
('549', 'Mineralogy', NULL),
('550', 'Earth sciences', NULL),
('551', 'Geology, hydrology, meteorology', NULL),
('552', 'Petrology', NULL),
('553', 'Economic geology', NULL),
('554', 'Earth sciences of Europe', NULL),
('555', 'Earth sciences of Asia', NULL),
('556', 'Earth sciences of Africa', NULL),
('557', 'Earth sciences of North America', NULL),
('558', 'Earth sciences of South America', NULL),
('559', 'Earth sciences of other areas', NULL),
('560', 'Paleontology', NULL),
('561', 'Paleobotany; fossil microorganisms', NULL),
('562', 'Fossil invertebrates', NULL),
('563', 'Fossil marine & seashore invertebrates', NULL),
('564', 'Fossil Mollucas & Molluscoidea', NULL),
('565', 'Fossil Arthropoda', NULL),
('566', 'Fossil Chordata', NULL),
('567', 'Fossil cold-blooded vertebrates', NULL),
('568', 'Fossil Aves (birds)', NULL),
('569', 'Fossil Mammalia', NULL),
('570', 'Biology', NULL),
('571', 'Physiology & related subjects', NULL),
('572', 'Biochemistry', NULL),
('573', 'Specific physiological systems in animals', NULL),
('574', '[Unassigned]', NULL),
('575', 'Specific parts of & systems in plants', NULL),
('576', 'Genetics and evolution', NULL),
('577', 'Ecology', NULL),
('578', 'Natural history of organisms', NULL),
('579', 'Microorganisms, fungi & algae', NULL),
('580', 'Plants', NULL),
('581', 'Specific topics in natural history of plants', NULL),
('582', 'Plants noted for characteristics & flowers', NULL),
('583', 'Eudicots and Ceratophyllales', NULL),
('584', 'Monocots, Chloranthales, magnoliids', NULL),
('585', 'Pinophyta', NULL),
('586', 'Cryptogamia', NULL),
('587', 'Pteridophyta', NULL),
('588', 'Bryophyta', NULL),
('589', '[Unassigned]', NULL),
('590', 'Animals', NULL),
('591', 'Specific topics in natural history of animals', NULL),
('592', 'Invertebrates', NULL),
('593', 'Marine & seashore invertebrates', NULL),
('594', 'Mollusca and Molluscoidea', NULL),
('595', 'Arthropoda', NULL),
('596', 'Chordata', NULL),
('597', 'Cold-blooded vertebrates', NULL),
('598', 'Aves', NULL),
('599', 'Mammalia', NULL),
('600', 'Technology (Applied sciences)', NULL),
('601', 'Philosophy and theory', NULL),
('602', 'Miscellany', NULL),
('603', 'Dictionaries, encyclopedias, concordances', NULL),
('604', 'Technical drawing, hazardous materials', NULL),
('605', 'Serial publications', NULL),
('606', 'Organizations', NULL),
('607', 'Education, research, related topics', NULL),
('608', 'Patents', NULL),
('609', 'History, geographic treatment, biography', NULL),
('610', 'Medicine and health', NULL),
('611', 'Human anatomy, cytology, histology', NULL),
('612', 'Human physiology', NULL),
('613', 'Personal health & safety', NULL),
('614', 'Forensic medicine; incidence of disease', NULL),
('615', 'Pharmacology and therapeutics', NULL),
('616', 'Diseases', NULL),
('617', 'Surgery & related medical specialties', NULL),
('618', 'Gynecology, obstetrics, pediatrics, geriatrics', NULL),
('619', '[Unassigned]', NULL),
('620', 'Engineering and allied operations', NULL),
('621', 'Applied physics', NULL),
('622', 'Mining and related operations', NULL),
('623', 'Military and nautical engineering', NULL),
('624', 'Civil engineering', NULL),
('625', 'Engineering of railroads and roads', NULL),
('626', '[Unassigned]', NULL),
('627', 'Hydraulic engineering', NULL),
('628', 'Sanitary engineering', NULL),
('629', 'Other branches of engineering', NULL),
('630', 'Agriculture and related technologies', NULL),
('631', 'Techniques, equipment & materials', NULL),
('632', 'Plant injuries, diseases, pests', NULL),
('633', 'Field and plantation crops', NULL),
('634', 'Orchards, fruits, forestry', NULL),
('635', 'Garden crops (Horticulture)', NULL),
('636', 'Animal husbandry', NULL),
('637', 'Processing dairy and related products', NULL),
('638', 'Insect culture', NULL),
('639', 'Hunting, fishing & conservation', NULL),
('640', 'Home and family management', NULL),
('641', 'Food and drink', NULL),
('642', 'Meals and table service', NULL),
('643', 'Housing and household equipment', NULL),
('644', 'Household utilities', NULL),
('645', 'Household furnishings', NULL),
('646', 'Sewing, clothing & personal living', NULL),
('647', 'Management of public households', NULL),
('648', 'Housekeeping', NULL),
('649', 'Child rearing & home care of people', NULL),
('650', 'Management and auxiliary services', NULL),
('651', 'Office services', NULL),
('652', 'Processes of written communication', NULL),
('653', 'Shorthand', NULL),
('654', '[Unassigned]', NULL),
('655', '[Unassigned]', NULL),
('656 ', '[Unassigned]', NULL),
('657', 'Accounting', NULL),
('658', 'General management', NULL),
('659', 'Advertising and public relations', NULL),
('660', 'Chemical engineering', NULL),
('661', 'Technology of industrial chemicals', NULL),
('662', 'Explosives, fuels & related products', NULL),
('663', 'Beverage technology', NULL),
('664', 'Food technology', NULL),
('665', 'Industrial oils, fats, waxes & gases', NULL),
('666', 'Ceramic & allied technologies', NULL),
('667', 'Cleaning, color & coating technologies', NULL),
('668', 'Technology of other organic products', NULL),
('669', 'Metallurgy', NULL),
('670', 'Manufacturing', NULL),
('671', 'Metalworking & primary metal products', NULL),
('672', 'Iron, steel, other iron alloys', NULL),
('673', 'Nonferrous metals', NULL),
('674', 'Lumber processing, wood products, cork', NULL),
('675', 'Leather and fur processing', NULL),
('676', 'Pulp and paper technology', NULL),
('677', 'Textiles', NULL),
('678', 'Elastomers and elastomer products', NULL),
('679', 'Other products of specific materials', NULL),
('680', 'Manufacture of products for specific uses', NULL),
('681', 'Precision instruments and other devices', NULL),
('682', 'Small forge work (Blacksmithing)', NULL),
('683', 'Hardware & household appliances', NULL),
('684', 'Furnishings and home workshops', NULL),
('685', 'Leather, fur goods & related products', NULL),
('686', 'Printing and related activities', NULL),
('687', 'Clothing and accessories', NULL),
('688', 'Other final products & packaging', NULL),
('689', '[Unassigned]', NULL),
('690', 'Construction of buildings', NULL),
('691', 'Building materials', NULL),
('692', 'Auxiliary construction practices', NULL),
('693', 'Specific materials & purposes', NULL),
('694', 'Wood construction', NULL),
('695', 'Roof covering', NULL),
('696', 'Utilities', NULL),
('697', 'Heating, ventilating & air-conditioning', NULL),
('698', 'Detail finishing', NULL),
('699', '[Unassigned]', NULL),
('700', 'The arts', NULL),
('701', 'Philosophy of fine & decorative arts', NULL),
('702', 'Miscellany of fine and decorative arts', NULL),
('703', 'Dictionaries of fine & decorative arts', NULL),
('704', 'Special topics in fine and decorative arts', NULL),
('705', 'Serial publications of fine & decorative arts', NULL),
('706', 'Organizations & management', NULL),
('707', 'Education, research & related topics', NULL),
('708', 'Galleries, museums & private collections', NULL),
('709', 'History, geographic treatment, biography', NULL),
('710', 'Area planning and landscape architecture', NULL),
('711', 'Area planning (Civic art)', NULL),
('712', 'Landscape architecture (Landscape design)', NULL),
('713', 'Landscape architecture of trafficways', NULL),
('714', 'Water features in landscape architecture', NULL),
('715', 'Woody plants in landscape architecture', NULL),
('716', 'Herbaceous plants', NULL),
('717', 'Structures in landscape architecture', NULL),
('718', 'Landscape design of cemeteries', NULL),
('719', 'Natural landscapes', NULL),
('720', 'Architecture', NULL),
('721', 'Architectural materials and structure', NULL),
('722', 'Architecture from earliest times to ca. 300', NULL),
('723', 'Architecture from ca. 300 to 1399', NULL),
('724', 'Architecture from 1400', NULL),
('725', 'Public structures', NULL),
('726', 'Buildings for religious and related purposes', NULL),
('727', 'Buildings for education & research', NULL),
('728', 'Residential and related buildings', NULL),
('729', 'Design & decoration', NULL),
('730', 'Sculpture and related arts', NULL),
('731', 'Processes, forms, subjects of sculpture', NULL),
('732', 'Sculpture to ca. 500', NULL),
('733', 'Greek, Etruscan, Roman sculpture', NULL),
('734', 'Sculpture from ca. 500 to 1399', NULL),
('735', 'Sculpture from 1400', NULL),
('736', 'Carving and carvings', NULL),
('737', 'Numismatics and sigillography', NULL),
('738', 'Ceramic arts', NULL),
('739', 'Art metalwork', NULL),
('740', 'Graphic arts and decorative arts', NULL),
('741', 'Drawing and drawings', NULL),
('742', 'Perspective in drawing', NULL),
('743', 'Drawing and drawings by subject', NULL),
('744', '[Unassigned]', NULL),
('745', 'Decorative arts', NULL),
('746', 'Textile arts', NULL),
('747', 'Interior decoration', NULL),
('748', 'Glass', NULL),
('749', 'Furniture and accessories', NULL),
('750', 'Painting and paintings', NULL),
('751', 'Techniques, equipment, materials & forms', NULL),
('752', 'Color', NULL),
('753', 'Symbolism, allegory, mythology, legend', NULL),
('754', 'Genre paintings', NULL),
('755', 'Religion', NULL),
('756', '[Unassigned]', NULL),
('757', 'Human figures', NULL),
('758', 'Nature, cityscapes & other subjects', NULL),
('759', 'History, geographic treatment, biography', NULL),
('760', 'Printmaking & prints', NULL),
('761', 'Relief processes (Block printing)', NULL),
('762', '[Unassigned]', NULL),
('763', 'Lithographic processes', NULL),
('764', 'Chromolithography and serigraphy', NULL),
('765', 'Metal engraving', NULL),
('766', 'Mezzotinting, aquatinting, related processes', NULL),
('767', 'Etching and drypoint', NULL),
('768', '[Unassigned]', NULL),
('769', 'Prints', NULL),
('770', 'Photography, computer art, cinematography', NULL),
('771', 'Techniques, equipment & materials', NULL),
('772', 'Metallic salt processes', NULL),
('773', 'Pigment processes of printing', NULL),
('774', 'Holography', NULL),
('775', '[Unassigned]', NULL),
('776', 'Computer art (Digital art)', NULL),
('777', 'Cinematography and videography', NULL),
('778', 'Specific fields & kinds of photography', NULL),
('779', 'Photographic images', NULL),
('780', 'Music', NULL),
('781', 'General principles and musical forms', NULL),
('782', 'Vocal music', NULL),
('783', 'Music for single voices', NULL),
('784', 'Instruments & instrumental ensembles', NULL),
('785', 'Ensembles with one instrument per part', NULL),
('786', 'Keyboard & other instruments', NULL),
('787', 'Stringed instruments (Chordophones)', NULL),
('788', 'Wind instruments (Aerophones)', NULL),
('789', '(Optional number)', NULL),
('790', 'Recreational and performing arts', NULL),
('791', 'Public performances', NULL),
('792', 'Stage presentations', NULL),
('793', 'Indoor games and amusements', NULL),
('794', 'Indoor games of skill', NULL),
('795', 'Games of chance', NULL),
('796', 'Athletic and outdoor sports and games', NULL),
('797', 'Aquatic and air sports', NULL),
('798', 'Equestrian sports and animal racing', NULL),
('799', 'Fishing, hunting, shooting', NULL),
('800', 'Literature (Belles-lettres) and rhetoric', NULL),
('801', 'Philosophy and theory', NULL),
('802', 'Miscellany', NULL),
('803', 'Dictionaries & encyclopedias', NULL),
('804', '[Unassigned]', NULL),
('805', 'Serial publications', NULL),
('806', 'Organizations and management', NULL),
('807', 'Education, research, related topics', NULL),
('808', 'Rhetoric & collections of literature', NULL),
('809', 'History, description & criticism', NULL),
('810', 'American literature in English', NULL),
('811', 'American poetry in English', NULL),
('812', 'American drama in English', NULL),
('813', 'American fiction in English', NULL),
('814', 'American essays in English', NULL),
('815', 'American speeches in English', NULL),
('816', 'American letters in English', NULL),
('817', 'American humor and satire in English', NULL),
('818', 'American miscellaneous writings', NULL),
('819', '(Optional number)', NULL),
('820', 'English & Old English literatures', NULL),
('821', 'English poetry', NULL),
('822', 'English drama', NULL),
('823', 'English fiction', NULL),
('824', 'English essays', NULL),
('825', 'English speeches', NULL),
('826', 'English letters', NULL),
('827', 'English humor and satire', NULL),
('828', 'English miscellaneous writings', NULL),
('829', 'Old English (Anglo-Saxon) literature', NULL),
('830', 'Literatures of Germanic languages', NULL),
('831', 'German poetry', NULL),
('832', 'German drama', NULL),
('833', 'German fiction', NULL),
('834', 'German essays', NULL),
('835', 'German speeches', NULL),
('836', 'German letters', NULL),
('837', 'German humor and satire', NULL),
('838', 'German miscellaneous writings', NULL),
('839', 'Other Germanic literatures', NULL),
('840', 'Literatures of Romance languages', NULL),
('841', 'French poetry', NULL),
('842', 'French drama', NULL),
('843', 'French fiction', NULL),
('844', 'French essays', NULL),
('845', 'French speeches', NULL),
('846', 'French letters', NULL),
('847', 'French humor and satire', NULL),
('848', 'French miscellaneous writings', NULL),
('849', 'Occitan, Catalan, Franco-Provençal', NULL),
('850', 'Italian, Romanian & related literatures', NULL),
('851', 'Italian poetry', NULL),
('852', 'Italian drama', NULL),
('853', 'Italian fiction', NULL),
('854', 'Italian essays', NULL),
('855', 'Italian speeches', NULL),
('856', 'Italian letters', NULL),
('857', 'Italian humor and satire', NULL),
('858', 'Italian miscellaneous writings', NULL),
('859', 'Romanian & related literatures', NULL),
('860', 'Spanish & Portuguese literatures', NULL),
('861', 'Spanish poetry', NULL),
('862', 'Spanish drama', NULL),
('863', 'Spanish fiction', NULL),
('864', 'Spanish essays', NULL),
('865', 'Spanish speeches', NULL),
('866', 'Spanish letters', NULL),
('867', 'Spanish humor and satire', NULL),
('868', 'Spanish miscellaneous writings', NULL),
('869', 'Portuguese and Galician literatures', NULL),
('870', 'Latin & related Italic literatures', NULL),
('871', 'Latin poetry', NULL),
('872', 'Latin dramatic poetry and drama', NULL),
('873', 'Latin epic poetry and fiction', NULL),
('874', 'Latin lyric poetry', NULL),
('875', 'Latin speeches', NULL),
('876', 'Latin letters', NULL),
('877', 'Latin humor and satire', NULL),
('878', 'Latin miscellaneous writings', NULL),
('879', 'Literatures of other Italic languages', NULL),
('880', 'Classical Greek & Hellenic literatures', NULL),
('881', 'Classical Greek poetry', NULL),
('882', 'Classical Greek dramatic poetry & drama', NULL),
('883', 'Classical Greek epic poetry and fiction', NULL),
('884', 'Classical Greek lyric poetry', NULL),
('885', 'Classical Greek speeches', NULL),
('886', 'Classical Greek letters', NULL),
('887', 'Classical Greek humor and satire', NULL),
('888', 'Classical Greek miscellaneous writings', NULL),
('889', 'Modern Greek literature', NULL),
('890', 'Literatures of other languages', NULL),
('891', 'East Indo-European and Celtic literatures', NULL),
('892', 'Afro-Asiatic literatures', NULL),
('893', 'Non-Semitic Afro-Asiatic literatures', NULL),
('894', 'Altaic, Uralic, Hyperborean & Dravidian', NULL),
('895', 'Literatures of East and Southeast Asia', NULL),
('896', 'African literatures', NULL),
('897', 'North American native literatures', NULL),
('898', 'South American native literatures', NULL),
('899', 'Austronesian & other literatures', NULL),
('900', 'History & geography', NULL),
('901', 'Philosophy and theory of history', NULL),
('902', 'Miscellany of history', NULL),
('903', 'Dictionaries & encyclopedias', NULL),
('904', 'Collected accounts of events', NULL),
('905', 'Serial publications of history', NULL),
('906', 'Organizations & management', NULL),
('907', 'Education, research & related topics', NULL),
('908', 'Groups of people', NULL),
('909', 'World history', NULL),
('910', 'Geography and travel', NULL),
('911', 'Historical geography', NULL),
('912', 'Maps and plans of surface of earth', NULL),
('913', 'Geography of & travel in ancient world', NULL),
('914', 'Geography of and travel in Europe', NULL),
('915', 'Geography of and travel in Asia', NULL),
('916', 'Geography of and travel in Africa', NULL),
('917', 'Geography of & travel in North America', NULL),
('918', 'Geography of & travel in South America', NULL),
('919', 'Geography of and travel in other areas', NULL),
('920', 'Biography, genealogy, insignia', NULL),
('921', '(Optional number) ', NULL),
('922', '(Optional number)', NULL),
('923', '(Optional number)', NULL),
('924', '(Optional number)', NULL),
('925', '(Optional number)', NULL),
('926', '(Optional number)', NULL),
('927', '(Optional number)', NULL),
('928', '(Optional number)', NULL),
('929', 'Genealogy, names & insignia', NULL),
('930', 'History of ancient world to ca. 499', NULL),
('931', 'China to 420', NULL),
('932', 'Egypt to 640', NULL),
('933', 'Palestine to 70', NULL),
('934', 'India to 647', NULL),
('935', 'Mesopotamia & Iranian Plateau to 637', NULL),
('936', 'Europe north & west of Italy to ca. 499', NULL),
('937', 'Italy & adjacent territories to 476', NULL),
('938', 'Greece to 323', NULL),
('939', 'Other parts of ancient world', NULL),
('940', 'History of Europe', NULL),
('941', 'British Isles', NULL),
('942', 'England and Wales', NULL),
('943', 'Germany & central Europe', NULL),
('944', 'France and Monaco', NULL),
('945', 'Italy, San Marino, Vatican City, Malta', NULL),
('946', 'Spain, Andorra, Gibraltar, Portugal', NULL),
('947', 'Russia & east Europe', NULL),
('948', 'Scandinavia and Finland', NULL),
('949', 'Other parts of Europe', NULL),
('950', 'History of Asia', NULL),
('951', 'China and adjacent areas', NULL),
('952', 'Japan', NULL),
('953', 'Arabian Peninsula and adjacent areas', NULL),
('954', 'India & south Asia', NULL),
('955', 'Iran', NULL),
('956', 'Middle East (Near East)', NULL),
('957', 'Siberia (Asiatic Russia)', NULL),
('958', 'Central Asia', NULL),
('959', 'Southeast Asia', NULL),
('960', 'History of Africa', NULL),
('961', 'Tunisia and Libya', NULL),
('962', 'Egypt, Sudan, South Sudan', NULL),
('963', 'Ethiopia and Eritrea', NULL),
('964', 'Morocco, Ceuta, Melilla, Western Sahara', NULL),
('965', 'Algeria', NULL),
('966', 'West Africa and offshore islands', NULL),
('967', 'Central Africa and offshore islands', NULL),
('968', 'South Africa & southern Africa', NULL),
('969', 'South Indian Ocean islands', NULL),
('970', 'History of North America', NULL),
('971', 'Canada', NULL),
('972', 'Mexico, Central America, West Indies', NULL),
('973', 'United States', NULL),
('974', 'Northeastern United States', NULL),
('975', 'Southeastern United States', NULL),
('976', 'South central United States', NULL),
('977', 'North central United States', NULL),
('978', 'Western United States', NULL),
('979', 'Great Basin & Pacific Slope region', NULL),
('980', 'History of South America', NULL),
('981', 'Brazil', NULL),
('982', 'Argentina', NULL),
('983', 'Chile', NULL),
('984', 'Bolivia', NULL),
('985', 'Peru', NULL),
('986', 'Colombia and Ecuador', NULL),
('987', 'Venezuela', NULL),
('988', 'Guiana', NULL),
('989', 'Paraguay and Uruguay', NULL),
('990', 'History of other areas', NULL),
('991', '[Unassigned]', NULL),
('992', '[Unassigned]', NULL),
('993', 'New Zealand', NULL),
('994', 'Australia', NULL),
('995', 'New Guinea & Melanesia', NULL),
('996', 'Polynesia & Pacific Ocean islands', NULL),
('997', 'Atlantic Ocean islands', NULL),
('998', 'Arctic islands and Antarctica', NULL),
('999', 'Extraterrestrial worlds ', NULL);